### PR TITLE
Canjs compatibility update

### PR DESCRIPTION
**Pull request by marshallswain**

### CODE REVIEW

**Comment by marshallswain** [comment]
As it sits right now, when using the latest CanJS (2.1.4), findAll and findOne return plain js objects.  This PR fixes that issue by changing findAll to makeFindAll.

**findOne still has an issue.**  I'm not quite sure how to fix it.  It wasn't as simple as changing findOne to makeFindOne.  

I've also updated the tests and included instructions in a new readme.md file on how to run them.  If you run the tests, you'll get the following result:
screen shot 2015-01-20 at 7 09 50 pm

The error is occurring when trying to run .attr() on the returned findOne data.  @daffl hopefully you will have some insight on what needs to be done.  It seems like you've been busy, but if you can give me an idea of what might be happening, I'll see what I can do.

**Comment by marshallswain** [comment]
Ok.  I was mistaken.  It's not fixing the findAll problem.  It's falling back to an Ajax request.

**Comment by marshallswain** [comment]
screenshot 2015-01-20 20 24 00

Tests are passing, now, but it's using Model.models and Model.model manually on the data.  I know those are deprecated, but I can't wrap my head around how to use makeFindAll and "pipe" into parseModels the way it says here: http://canjs.com/docs/can.Model.parseModels.html

So this is a fix, but it's a temporary one.

**Comment by marshallswain** [comment]
As a result of this current "fix" is that you can no longer use this syntax:
```js
model.findAll({}, function(dbs){ // Just note this line.
	self.attr('databases').replace(dbs);
	dbDef.resolve(dbs);
});
```
But instead have to use then():
```js
model.findAll({}).then(function(dbs){  // Just note this line.
	self.attr('databases').replace(dbs);
	dbDef.resolve(dbs);
});
```

**Comment by marshallswain** [comment]
I've updated this to use makeFindAll() and makeFindOne().  All tests are passing.  It's still using model() and models() manually.

**Comment by marshallswain** [comment]
Justin let me know in the CanJS Gitter chat that makeFindAll() is supposed to still use models() manually.  Same for makeFindOne and model(), so this is done.

**Comment by daffl** [comment]
Would this still work with older versions? Oh, I'd also like to use https://github.com/feathersjs/feathers-websocket-client here for the next version to consolidate things a little bit.

**Comment by marshallswain** [comment]
I tested with CanJS 2.1.4 and 2.0.  All tests pass. 
I tested with CanJS 1.1.7.  All the CRUD tests pass, but the tests for live binding choke because can.view.mustache() doesn't exist.

**Comment by marshallswain** [comment]
Can you publish feathers-websocket-client to [Bower](http://bower.io/search/?q=feathers-websocket-client)?

**Comment by daffl** [comment]
Yep, will do. You can merge your PRs already though and tag a new version. We'll migrate it after that (and make a new release).

**Comment by marshallswain** [comment]
Cool.  I did a little prep work for publishing feathers-websocket-client to bower here: https://github.com/feathersjs/feathers-websocket-client/pull/2

**Pull request merged**
