### PR TITLE
Like can-connect, but uses feathers-client.

### PR DESCRIPTION
**Pull request by marshallswain**
I created a demo app here: https://github.com/icanjs/steal-can3-feathers.
It's laid out just like a DoneJS app, but without the SSR.  It just needs a generated feathers app with an `accounts` service.

Also, check out the readme for example usage: https://github.com/feathersjs/canjs-feathers/tree/feathers-client

### CODE REVIEW

**Comment by daffl** [comment]
Once the conflicts are resolved and tests are passing I'd say :shipit: (there is a 1.0.0-pre in there, is that the same release?)

**Comment by marshallswain** [comment]
Yeah. That's the same one. Any idea why the testee tests aren't running in
Travis?

**Comment by marshallswain** [comment]
The tests look the same as other modules that are working, so I don't know
what's going on.

**Comment by marshallswain** [comment]
I mean the Travis setup and eat scripts in the package.json

**Pull request merged**
